/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud.pkg2;

import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.Timer;

/**
 *
 * @author Yuzron
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        SetJam();
        setTanggal();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
   public void setTanggal() { //method untuk menampilkan tanggal
       java.util.Date skrg = new java.util.Date();
       java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
       txtTanggal.setText(kal.format(skrg));
   }
   
   public void SetJam(){ //method untuk jam
       ActionListener taskPerformer = new ActionListener() { //ActionListener untuk keperluan timer
        public void actionPerformed(ActionEvent evt) {
            Date dt = new Date(); //membuat Date
            int nilai_jam = dt.getHours(); //mengambil nilai jam, menit, dan detik sekarang
            int nilai_menit = dt.getMinutes(); 
            int nilai_detik = dt.getSeconds();
            String nol_jam ="";
            String nol_menit ="";
            String nol_detik ="";
            if(nilai_jam <= 9) { //jika nilai jam lebih kecil dari 10 (hanya 1 digit)
                nol_jam = "0"; //untuk menambahkan "0" didepannya
            }
            if(nilai_menit <= 9) { //jika nilai menit lebih kecil dari 10 (hanya 1 digit)
                nol_menit = "0"; //untuk menambahkan "0" didepannya
            }
            if(nilai_detik <= 9) { //jika nilai detik lebih kecil dari 10 (hanya 1 digit)
                nol_detik = "0"; //untuk menambahkan "0" didepannya
            }
            //membuat String jam , menit, dan detik
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
            txtJam.setText("Jam "+jam + ":" +menit+":"+detik); //menampilkan pada label layar
        }  
}; new Timer(100, taskPerformer).start();//Timer   
   }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtJam = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jIDbarang = new javax.swing.JTextField();
        jNama = new javax.swing.JTextField();
        jJumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jHarga = new javax.swing.JTextField();
        jTanggal = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBiodata = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        bsave = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        brefresh = new javax.swing.JButton();
        bPrint = new javax.swing.JButton();
        jTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JUAL BELI TOKO MEKAR MAKMUR");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 10, 450, 29);

        txtJam.setFont(new java.awt.Font("Baskerville Old Face", 1, 13)); // NOI18N
        txtJam.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtJam);
        txtJam.setBounds(530, 60, 100, 14);

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("JUAL BANYAK BARANG");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 70, 200, 14);

        txtTanggal.setFont(new java.awt.Font("Baskerville Old Face", 1, 13)); // NOI18N
        txtTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtTanggal);
        txtTanggal.setBounds(530, 40, 100, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 90);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("KASIR TRANSAKSI");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 10, 140, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 110, 260, 30);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ID BARANG");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 14);
        jPanel3.add(jIDbarang);
        jIDbarang.setBounds(10, 40, 110, 20);
        jPanel3.add(jNama);
        jNama.setBounds(10, 90, 190, 20);
        jPanel3.add(jJumlah);
        jJumlah.setBounds(10, 220, 190, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nama Barang");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 70, 140, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 250, 140, 14);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Harga");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 130, 160, 14);
        jPanel3.add(jHarga);
        jHarga.setBounds(10, 150, 150, 20);
        jPanel3.add(jTanggal);
        jTanggal.setBounds(10, 270, 190, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Jumlah");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 190, 140, 14);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 150, 270, 590);

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel4.setLayout(null);

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IDBarang", "NamaBarang", "HargaBarang", "JumlahBarang", "HargaxTotal", "Tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTransaksi);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(40, 240, 570, 130);

        tableBiodata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IDBarang", "NamaBarang", "HargaBarang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBiodata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBiodataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBiodata);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(40, 70, 570, 130);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(290, 170, 630, 580);

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));
        jPanel5.setLayout(null);

        bsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel5.add(bsave);
        bsave.setBounds(20, 10, 80, 30);

        bclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bclear.setText("CLEAR");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel5.add(bclear);
        bclear.setBounds(120, 10, 80, 30);

        brefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brefresh.setText("REFRESH");
        brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brefreshActionPerformed(evt);
            }
        });
        jPanel5.add(brefresh);
        brefresh.setBounds(230, 10, 100, 30);

        bPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        jPanel5.add(bPrint);
        bPrint.setBounds(500, 3, 80, 40);

        jTransaksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTransaksi.setText("TRANSAKSI");
        jTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTransaksiActionPerformed(evt);
            }
        });
        jPanel5.add(jTransaksi);
        jTransaksi.setBounds(350, 10, 130, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(300, 110, 630, 50);

        setSize(new java.awt.Dimension(943, 791));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = dateFormat.format(jTanggal.getDate());
            //String harga = jHarga.getText();
            //String jumlah = jJumlah.getText();
            int harga=Integer.parseInt(jHarga.getText());
            int jumlah = Integer.parseInt(jJumlah.getText());
            int hargaxjumlah = harga * jumlah ;
            if("".equals(jIDbarang.getText()) || "".equals(jNama.getText()) || "".equals(jJumlah.getText()) || "".equals(jHarga.getText()) || "".equals(tanggal)) {
                JOptionPane.showMessageDialog(this, "Harap lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
                
                
             String SQL = "INSERT INTO transaksi (nama_barang,harga_barang,jumlah_barang,hargaxjumlah,tanggal)"
                     + "VALUES ('"+jNama.getText()+"',"+jHarga.getText()+","+jJumlah.getText()+","+hargaxjumlah+",'"+tanggal+"')";
            
             int status = KoneksiDB.execute(SQL);
             if (status==1){
                 JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "SUkses", JOptionPane.INFORMATION_MESSAGE);
                 selectTransaksi();
             } else {
                 JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
                 
             }
            }
            
    }//GEN-LAST:event_bsaveActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        jIDbarang.setText("");
        jNama.setText("");
        jJumlah.setText("");
        jHarga.setText("");
        
    }//GEN-LAST:event_bclearActionPerformed

    private void brefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brefreshActionPerformed
        selectData();
        
    }//GEN-LAST:event_brefreshActionPerformed

    public void selectData() {
            String kolom[] = {"IDBarang","NamaBarang","HargaBarang"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM barang";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String IDBarang = rs.getString(1);
                String NamaBarang = rs.getString(2);
                String HargaBarang = rs.getString(3);
                //String Email = rs.getString(5);
                //String Alamat = rs.getString(6);
                String data[] = {IDBarang,NamaBarang,HargaBarang};
                dtm.addRow(data);
            }
            } catch (SQLException ex) {
                
        }tableBiodata.setModel(dtm);
    
    }
    private void selectTransaksi() {
        String kolom[] = {"IDBarang","NamaBarang","HargaBarang","JumlahBarang","HargaxJumlah","Tanggal"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String IDBarang = rs.getString(1);
                String NamaBarang = rs.getString(2);
                String HargaBarang = rs.getString(3);
                String JumlahBarang = rs.getString(4);
                String HargaxJumlah = rs.getString(5);
                String Tanggal = rs.getString(6);
                String data[] = {IDBarang,NamaBarang,HargaBarang,JumlahBarang,HargaxJumlah,Tanggal};
                dtm.addRow(data);
            }
            } catch (SQLException ex) {
                
        }tableTransaksi.setModel(dtm);
    
    }
    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        MessageFormat header= new MessageFormat("STRUK BELANJA TOKO MEKAR MAKMUR");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}        ");
        try{
            tableTransaksi.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bPrintActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
           
        

    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void tableBiodataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBiodataMouseClicked
        int baris = tableBiodata.getSelectedRow();
        if (baris != -1) {
            jIDbarang.setText(tableBiodata.getValueAt(baris, 0).toString());
            jNama.setText(tableBiodata.getValueAt(baris, 1).toString());
        }
        jHarga.setText(tableBiodata.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_tableBiodataMouseClicked

    private void jTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTransaksiActionPerformed
       selectTransaksi();
    }//GEN-LAST:event_jTransaksiActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bclear;
    private javax.swing.JButton brefresh;
    private javax.swing.JButton bsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jHarga;
    private javax.swing.JTextField jIDbarang;
    private javax.swing.JTextField jJumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jTanggal;
    private javax.swing.JButton jTransaksi;
    private javax.swing.JTable tableBiodata;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JLabel txtJam;
    private javax.swing.JLabel txtTanggal;
    // End of variables declaration//GEN-END:variables

    
    
}
